### ISSUE TITLE
文件名出错

### ISSUE THREAD

**Issue by luosiwei-cmd** [optimize-2/Crayon#2]
example，谢谢！不是exsample……

**Comment by optimize-2** [comment]
thks
but gugugugu




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "optimize-2/Crayon"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午5:53
收件人:&nbsp;"optimize-2/Crayon"<Crayon@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[optimize-2/Crayon] 文件名出错 (#2)





 
example，谢谢！不是exsample……

**Comment by luosiwei-cmd** [comment]
我谔谔
