### ISSUE TITLE
cyrand 产生的随机数不均匀

### ISSUE THREAD

**Issue by Henry-ZHR** [optimize-2/Crayon#3]
如题

还有，标准库都有的东西为啥要重复造轮子

**Comment by optimize-2** [comment]
您是指cyrand还是cyrand_ll?
cyrand循环节更大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "optimize-2/Crayon"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月8日(星期六) 上午10:26
收件人:&nbsp;"optimize-2/Crayon"<Crayon@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[optimize-2/Crayon] cyrand 产生的随机数不均匀 (#3)





 
如题
 
还有，标准库都有的东西为啥要重复造轮子

**Comment by Henry-ZHR** [comment]
都是

不是循环节

得到的数概率不一样

**Comment by optimize-2** [comment]
怎么得出这个结论的/yiw




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "optimize-2/Crayon"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月8日(星期六) 中午11:58
收件人:&nbsp;"optimize-2/Crayon"<Crayon@noreply.github.com&gt;;
抄送:&nbsp;"optimize_谔"<2086297211@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [optimize-2/Crayon] cyrand 产生的随机数不均匀 (#3)





 
都是
 
不是循环节
 
得到的数概率不一样

**Comment by Henry-ZHR** [comment]
建议参考 [std::uniform_int_distribution](https://zh.cppreference.com/w/cpp/numeric/random/uniform_int_distribution) 的实现

**Comment by optimize-2** [comment]
ok


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "optimize-2/Crayon"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月8日(星期六) 中午11:59
收件人:&nbsp;"optimize-2/Crayon"<Crayon@noreply.github.com&gt;;
抄送:&nbsp;"optimize_谔"<2086297211@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [optimize-2/Crayon] cyrand 产生的随机数不均匀 (#3)





 
建议参考 std::uniform_int_distribution 的实现

**Comment by Henry-ZHR** [comment]
> 
> 怎么得出这个结论的/yiw
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "optimize-2/Crayon" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月8日(星期六) 中午11:58 收件人:&nbsp;"optimize-2/Crayon"<Crayon@noreply.github.com&gt;; 抄送:&nbsp;"optimize_谔"<2086297211@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [optimize-2/Crayon] cyrand 产生的随机数不均匀 (#3) 都是 不是循环节 得到的数概率不一样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

假设 `MTrand` 等概率产生 1 到 3 的整数，然后你模一个 2，这样的话得到的 1 的概率是 2/3，得到 0 的概率是 1/3，概率就会不一样

当然，你本身范围比这个大很多，这个不会很明显地体现出来，但如果想给别人用的话还是建议注意一下

**Comment by Henry-ZHR** [comment]
（你这项目貌似小毛病挺多，我只是刚好看到这个就过来发了

**Comment by optimize-2** [comment]
哦
thks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "optimize-2/Crayon"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月8日(星期六) 中午12:05
收件人:&nbsp;"optimize-2/Crayon"<Crayon@noreply.github.com&gt;;
抄送:&nbsp;"optimize_谔"<2086297211@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [optimize-2/Crayon] cyrand 产生的随机数不均匀 (#3)





 
（你这项目貌似小毛病挺多，我只是刚好看到这个就过来发了
